### ISSUE TITLE
How to request data from connected Server?

### ISSUE THREAD

**Issue by freevoltage** [SiliconLabs/pybgapi#1]
# Issue Summary

I am facing a problem with my BLE Client's data request to a BLE Server. The issue is related to the `pybgapi` library, and I need assistance in resolving it.

[This issue was originally posted in the [bgapi repository](https://github.com/mjbrown/bgapi/issues/53). However I think it is better suited at this repository because I am using the example code of pybgapi]

### Here is the relevant code snippet:

```
if self.conn_state == "enable_indication":
    # ...
    self.lib.bt.gatt.read_characteristic_value(
        evt.connection, SENSOR_DATA_CHARACTERISTIC)
```

The Client is requesting data from the connected Server via a gatt client functions from the [Bluetooth API Reference Guide](https://docs.silabs.com/bluetooth/latest/bluetooth-stack-api/sl-bt-gatt).

I expect that a BLE stack event will be triggered on the client and I can extract the data from the event.

The SENSOR_DATA_CHARACTERISTIC variable is defined as:
```
#UUID = 34850bc9-95e5-4701-956c-656ce1afdc66
SENSOR_DATA_CHARACTERISTIC = b"\x66\xdc\xaf\xe1\x6c\x65\x6c\x95\x01\x47\xe5\x95\xc9\x0b\x85\x34"
```
I am encountering the following error:

```
File "/Users/username/Documents/GitHub/pybgapi-examples/lib/python3.11/site-packages/bgapi/apiparser.py", line 30, in toInt
    return int(s)
ValueError: invalid literal for int() with base 10: b'f\xdc\xaf\xe1lel\x95\x01G\xe5\x95\xc9\x0b\x854'
```

I also tried another variant where I casted the byte to an integer value, but I guess this was not a good idea neither.

```
    self.lib.bt.gatt.read_characteristic_value(
        evt.connection, int.from_bytes(SENSOR_DATA_CHARACTERISTIC, byteorder='little'))
```

Thank you for any advice in solving this issue and let me know if you need more information.

**Comment by silabs-beta** [comment]
The `read_characteristic_value` command expects a GATT characteristic handle as its second parameter, which is a 16 bit integer and not a UUID. See also [here](https://docs.silabs.com/bluetooth/latest/bluetooth-stack-api/sl-bt-gatt#sl-bt-gatt-read-characteristic-value). I.e., the service handle and the characteristic handle has to be discovered first. You can use the [bt_thermometer_client](https://github.com/SiliconLabs/pybgapi-examples/tree/master/example/bt_thermometer_client) example as reference.
Please also note that the [bgapi](https://github.com/mjbrown/bgapi) repo is not a Silicon Labs product, its content is most probably outdated.

**Comment by freevoltage** [comment]
I understand. thank you for the support.

(Regarding BGAPI. Do you offer an API which is still maintained? Or are there alternatives of which you know?)

**Comment by silabs-beta** [comment]
Sure, this repo is maintained actively, which contains the source of the [pybgapi](https://pypi.org/project/pybgapi/) package.
Make sure to uninstall bgapi package first before you install the pybgapi package, there could be conflicts otherwise.
We also have some example applications in the [pybgapi-examples](https://github.com/SiliconLabs/pybgapi-examples) repo.
