### ISSUE TITLE
How to request multiple characteristic values?

### ISSUE THREAD

**Issue by freevoltage** [SiliconLabs/pybgapi#2]
# Issue Summary

I am facing a problem that I am unable to use the **read_multiple_characteristic_values** function from PYBGAPI. The documentation is rough and I couldn't find any examples of usage. 

## Environment Information
- PYBGAPI Version: 1.2.0
- Python Version: 3.9.6

## Relevant Code Snippet

For simplicity I just use **connection_handle=1**.
As I understand the argument **characteristic_list_len** would be the just the length of the characteristic_list
and

```
characteristic_list = [self.conn_properties[1][CHARACTERISTICS_1_HANDLE], self.conn_properties[1][CHARACTERISTICS_2_HANDLE]]
# Characteristic list will be: [35, 40]
        self.lib.bt.gatt.read_multiple_characteristic_values(1, len(characteristic_list), characteristic_list)

```

The API call does fail with an `IndexError: list index out of range`. However I also tried to make sure that the **characteristic_handle** is formatted as little_endian with

```
characteristic_list = [struct.pack('H', char_handle) for char_handle in characteristic_list]
```
before calling `self.lib.bt.gatt.read_multiple_characteristic_values(1, len(characteristic_list), characteristic_list)`

The error is still the same. I also tried to set the length to zero and a couple of other things but the error was always the same.

I would appreciate any help to resolve the issue

Thank you and Best Regards

**Comment by silabs-beta** [comment]
There are some differences how to use BGAPI in C and in Python. 
The origin of both languages is the common XML descriptor of the BGAPI. [Here](https://github.com/SiliconLabs/pybgapi-examples/blob/master/api/sl_bt.xapi#L1662) you can see that the `characteristic_list` parameter of the `read_multiple_characteristic_values` command is a single parameter with a type of uint8array.
In C, you pass arrays as 2 arguments due to language constraints: a length and a pointer.
In Python, however, arrays are list object that have the length info embedded, so there is no need to pass the length in a separate argument.
Please try to omit the `len(characteristic_list)` argument in your code.

**Comment by freevoltage** [comment]
Thank you for the help. I appreciate it. 

However it seems that just removing the `len(characteristic_list)` is not enough. The runtime will throw an `AttributeError`. You can see the line within the API where it is referring to below. 
```
File "/Users/my_username/path_to_project/.venv-pybgapi/lib/python3.9/site-packages/bgapi/serdeser.py", line 47, in to_bytes
    return s.encode("latin-1")
AttributeError: 'list' object has no attribute 'encode'
```

in my context: The values of `characteristic_list = [self.conn_properties[1][CHARACTERISTICS_1_HANDLE], self.conn_properties[1][CHARACTERISTICS_2_HANDLE]]` is a list containing `[35, 40]`

In my investigation of the problem I've tried to modify it with:
```
characteristic_list = [self.conn_properties[1][CHARACTERISTICS_1_HANDLE], self.conn_properties[1]
[CHARACTERISTICS_2_HANDLE]]
characteristic_list = [int.to_bytes(characteristic, length=8, byteorder='little') for characteristic in characteristic_list]
self.lib.bt.gatt.read_multiple_characteristic_values(1, characteristic_list)
```

*But then got the idea that it is actually the list object which is causing the Error not the elements within (obvious after thinking about that)* 

I thought "maybe I just convert the list to bytes?" 
with

```
characteristic_list = [self.conn_properties[1][CHARACTERISTICS_1_HANDLE], self.conn_properties[1]
[CHARACTERISTICS_2_HANDLE]]
self.lib.bt.gatt.read_multiple_characteristic_values(1, bytes(characteristic_list))
```

and indeed this time the command went thru, but the expected event [sl_bt_evt_gatt_characteristic_value](https://docs.silabs.com/bluetooth/latest/bluetooth-stack-api/sl-bt-evt-gatt-characteristic-value) was not triggered. 

So I need to again ask for guidance with "how to do this API call properly".

**Comment by freevoltage** [comment]
Ah I think I got the solution!

```
characteristic_list = [
    self.conn_properties[1][CHARACTERISTICS_1_HANDLE],
    self.conn_properties[1][CHARACTERISTICS_2_HANDLE]
    ]
# Convert each characteristic handle to little-endian bytes
characteristic_list_bytes = [handle.to_bytes(2, 'little') for handle in characteristic_list]
# Flatten the list of byte arrays into a single bytearray
characteristic_list_bytes = b''.join(characteristic_list_bytes)
        
self.lib.bt.gatt.read_multiple_characteristic_values(1, characteristic_list_bytes)

```

I need to update my event processing mechanisms now and then I should be able to request the characteristic values successfully.

Thank you for advice.

**Comment by silabs-beta** [comment]
Indeed, this has been a tricky one.
Thank you for taking the time to give feedback, this helps us improving the developer experience.
